title: learn.tunjos.co
description: Tunjos Learn
author: tunjos
author_name: Tunji Olu-Taiwo
logo: https://tunjos.co/static/img/headshot.jpg
github: https://github.com/tunjos
about: Happiness Engineer..Critical Thinker.
disqus_shortname:
google_analytics:
plain_url: tunjos.co
plain_url2: tunjos.com
urls:
    - text: Home
      url: 'https://tunjos.co'
      icon: fa-home
      layout: post
    - text: About
      url: 'https://tunjos.co/about'
      icon: fa-info
    - text: Learn
      url: /
      icon: fa-book
    - text: Clean Architecture
      url: /clean-architecture/
      icon: fa-circle
    - text: Machine Learning
      url: /machine-learning/
      icon: fa-spinner
    - text: Artrificial Intelligence
      url: /artificial-intelligence/
      icon: fa-gear
    - text: Security
      url: /security/
      icon: fa-lock
    - text: Cryptography
      url: /cryptography/
      icon: eye-slash
    - text: GIT
      url: /git
      icon: fa-git
    - text: Android
      url: /android/
      icon: fa-android
    - text: Java
      url: /java/
      icon: fa-coffee
    - text: Kotlin
      url: /kotlin/
      icon: fa-question
    - text: Vue.js
      url: /vue/
      icon: fa-caret-down
    - text: Python
      url: /python/
      icon: fa-indent
    - text: Github
      url: https://github.com/tunjos
      icon: fa-github
      target: _blank

social:
    - icon: fa-twitter
      link: 'https://twitter.com/tunjos'
    - icon: fa-github
      link: 'https://github.com/tunjos'
    - icon: fa-linkedin
      link: 'https://www.linkedin.com/in/tunjos'
    - icon: fa-stack-exchange
      link: '#'
    - links:
      - https://twitter.com/tunjos
      - https://github.com/tunjos
      - https://www.linkedin.com/in/tunjos
#      -https://stackexchange.com/users/000000/abcdef

share:
  twitter_username: tunjos
  fb_appid: 000000000000


enableTags: true
tagarray: []

#url: "http://localhost:4000"
url: "https://tunjos.co"
baseurl: ""
paginate: 5
per_page: 5
paginate_path: "/page:num/"
permalink: /blog/:title/
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
exclude: [_drafts/help]

#jekyll-seo-tag
twitter:
  username: tunjos
  card: summary
lang: en_GB
